name: cormorants3
channels:
  - defaults
dependencies:
  - geopandas=0.9.0=py_1
  - matplotlib=3.5.0=py37hecd8cb5_0
  - networkx=2.6.2=pyhd3eb1b0_0
  - pandas=1.3.2=py37h5008ddb_0
  - pillow=9.0.1=py37hde71d04_0
  - pip=21.2.2=py37hecd8cb5_0
  - shapely=1.7.1=py37h9250791_0
  - pip:
    - numpy==1.18.5
    - object-detection==0.1
    - tensorflow==2.2.3
    - tqdm==4.62.2
